# Generated by Django 3.0.4 on 2020-03-20 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('ID_animal', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('race', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=6)),
                ('size', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('a', 'for_adoption'), ('f', 'found'), ('l', 'lost')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID_user', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=200)),
                ('Mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone', models.CharField(max_length=10)),
                ('ID_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Area', models.CharField(max_length=200)),
                ('cellphone', models.CharField(max_length=200)),
                ('ID_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Animal')),
                ('ID_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
