# Generated by Django 3.0.4 on 2020-03-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200325_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='ID_animal',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
