# Generated by Django 3.0.4 on 2020-03-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200325_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Mail',
        ),
        migrations.AddField(
            model_name='user',
            name='ProfilePic',
            field=models.ImageField(default='main/static/media/user/rey.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='UserName',
            field=models.CharField(default='Pedro', max_length=200),
        ),
    ]
