# Generated by Django 3.0.4 on 2020-03-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200328_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(default='Pedro', max_length=200),
        ),
    ]
