# Generated by Django 3.0.4 on 2020-03-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200328_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ProfilePic',
            field=models.ImageField(default='main/static/media/user/rey.png', upload_to=''),
        ),
    ]
