# Generated by Django 3.0.4 on 2020-03-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200328_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ProfilePic',
            field=models.ImageField(default='main/static/media/user/rey.png', upload_to='main/static/media/user/'),
        ),
    ]
