# Generated by Django 3.0.4 on 2020-03-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200329_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='cellphone',
        ),
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.ImageField(default='main/static/media/animal/rey.png', upload_to='main/static/media/animal/'),
        ),
    ]
