# Generated by Django 3.0.4 on 2020-03-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200329_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.CharField(choices=[('s', 'short'), ('m', 'medium'), ('b', 'big')], default='Description Example', max_length=500),
        ),
    ]
