# Generated by Django 3.0.4 on 2020-03-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_animal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ProfilePic',
            field=models.ImageField(default='main/static/media/user/rey.png', upload_to='user/'),
        ),
    ]
