# Generated by Django 3.0.4 on 2020-03-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200330_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.FileField(default='animal/rey.png', upload_to='animal/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ProfilePic',
            field=models.FileField(default='user/rey.png', upload_to='user/'),
        ),
    ]
